target-version = "py310"
extend-exclude = ["*.stop"]
line-length = 100

[lint]
select = ["ANN", "D", "E", "F", "FIX", "I", "Q", "S", "W"]
extend-select = ["D204"]
ignore = [
    "ANN002", # missing-type-args (for *args)
    "ANN003", # missing-type-kwargs
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    # "D202", # blank-line-after-function
    # "D203", # incorrect-blank-line-before-class
    # "D205", # missing-blank-line-after-summary
    # "D211", # blank-line-before-class
    # "D212", # multi-line-summary-first-line
    "D213", # multi-line-summary-second-line
    "S603", # `subprocess` call: check for execution of untrusted input
]

[lint.per-file-ignores]
"tests/*" = [
    "S101",   # Use of `assert` detected
]

[lint.isort]
force-sort-within-sections = true
lines-after-imports = 2

[lint.pydocstyle]
convention = "google"
